server:
  port: 8090
spring:
  datasource:
    #    SQLServer 相关配置信息
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///babyshop?characterEncoding=utf8&useUnicode=true
    #    url: jdbc:mysql://rm-m5e01hh28l500t4u6.mysql.rds.aliyuncs.com:3306/lk?characterEncoding=utf8&useUnicode=true
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 1
      test-on-borrow: true
      stat-view-servlet.allow: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: cn.suse.edu.baby.pojo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #实体类属性自动填充
    meta-object-handler: com.lk.cloud.common.handler.FillEntityHandler
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl